### ISSUE TITLE
Updating to 0.16.1 produces Unexpected token. Reverting to 0.15.1

### ISSUE THREAD

**Issue by cmoedk** [ezolenko/rollup-plugin-typescript2#100]
#### What happens and why it is wrong
Running a build produces the error: 
```
[!] SyntaxError: Unexpected token =
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions..js (G:\programming\git\decathlon\node_modules\rollup\bin\rollup:1214:17)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (G:\programming\git\decathlon\rollup-debug-build.config.js:7:34)
    at Module._compile (module.js:435:26)
```

#### Versions
- typescript: 2.9.2
- rollup: 0.63.4
- rollup-plugin-typescript2: 0.16.1

#### rollup.config.js
```
export default {
    input: 'src/main.ts',
    output: {
        sourcemap : false,
        format: 'iife'
    },
    preferConst: true,
    plugins: [
        typescript(/*{ plugin options }*/),
        strip({
            // set this to `false` if you don't want to
            // remove debugger statements
            debugger: true,

            // defaults to `[ 'console.*', 'assert.*' ]`
            functions: [
                'console.*',
                'debug',
                'DEBUG'
            ],

            // set this to `false` if you're not using sourcemaps –
            // defaults to `true`
            sourceMap: false
        }),
        uglify({}, minify)
    ]
};

export default {
    input: rollupConfig.input,
    output: {
        intro: 'const VERSION = "' + pkg.version + '";',
        file: 'dev/js/decathlon.js',
        sourcemap: 'inline',
        format: rollupConfig.output.format
    },
    preferConst: rollupConfig.preferConst,
    plugins: [
        typescript(/*{ plugin options }*/)
    ]
};

```
#### tsconfig.json
```
{
  "compilerOptions": {
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny" : true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "module": "es6",
    "moduleResolution": "node",
    "target": "es6",
    "sourceMap": true,
    "lib": ["dom", "es2016", "es2016.array.include"]
  },
  "files" : [
    "./src/main.ts"
  ]
}
```
#### package.json
```
"devDependencies": {
    "@types/gsap": "^1.19.2",
    "@types/jquery": "^3.3.1",
    "mkdirp": "^0.5.1",
    "ncp": "^2.0.0",
    "rollup": "^0.63.4",
    "rollup-plugin-strip": "^1.1.1",
    "rollup-plugin-typescript2": "^0.15.1",
    "rollup-plugin-uglify": "^3.0.0",
    "stylus": "^0.54.5",
    "typescript": "^2.9.2",
    "uglify-es": "^3.3.9",
    "tslib": "^1.9.3"
  },
```

**Comment by ezolenko** [comment]
Could you make a basic repo that reproduces it? Or point to the full repo if it is open source.

**Comment by cmoedk** [comment]
I will need to dig a bit deeper. It seems 0.16.1 works fine on my laptop, but produces the above error on my desktop. I don't know right now what the difference is between the two setups. Maybe it's the node version? I will check, when I get the time.

**Comment by cmoedk** [comment]
I updated node.js (and webstorm), and now it seems to work.

**Comment by ezolenko** [comment]
Ah, yes, it needs newer node now, with es2015 support.
