### ISSUE TITLE
`rollup` cache freezes -- code has error in it

### ISSUE THREAD

**Issue by sbfkcel** [ezolenko/rollup-plugin-typescript2#102]
`rollup ver 0.63.5`
`rollup-plugin-typescript2 ver 0.16.1`

`npm run dev`
[rollupTest.zip](https://github.com/ezolenko/rollup-plugin-typescript2/files/2259186/rollupTest.zip)

The first compilation is normal, because the rollup cache is null at this time, and it will be frozen the second time there is a cache.

**Comment by ezolenko** [comment]
Doesn't seem to finish if I delete cache and even disable it.

**Comment by ezolenko** [comment]
That is, it prints `compileTime: X ms`, but never exits and doesn't seem to be watching either. This is on windows if that makes a difference.

**Comment by sbfkcel** [comment]
- `npm install`
- `npm run dev`Will listen for file changes and compile for the first time
-  Try modifying `src/index.tsx` (the listener will be modified for a second time) and there will be a cache. Will be frozen

**Comment by ezolenko** [comment]
Yep, I reproduced it, thanks.

**Comment by agilgur5** [comment]
I took a look at this and one of the issues here is that TS has a fatal error on this code since types aren't provided for `react` and `react-dom`:

```
❯ npm run build

> rolluptest@1.0.0 build
> rollup -c


./src/index.ts → ./dist/index.ts...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
src/index.ts (1:7)
[!] Error: 'default' is not exported by node_modules/react/index.js, imported by src/index.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/index.ts (1:7)
1: import React from 'react';
          ^
2: import ReactDom from 'react-dom';
3: console.log(React, ReactDom);
Error: 'default' is not exported by node_modules/react/index.js, imported by src/index.ts
    at error (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:12553:16)
    at Module.traceVariable (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:12912:29)
    at ModuleScope.findVariable (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:11564:39)
    at Identifier.bind (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:7553:40)
    at CallExpression.bind (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:5379:73)
    at CallExpression.bind (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:9048:15)
    at ExpressionStatement.bind (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:5383:23)
    at Program.bind (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:5379:73)
    at Module.bindReferences (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:12549:18)
```

So rpt2 aborts the Rollup process and no bundle is produced. So that is correct behavior.

A `tsconfig.json` is also missing, so even if `@types/react` and `@types/react-dom` are installed, you'll hit another error:
```
❯ npm run build

> rolluptest@1.0.0 build
> rollup -c


./src/index.ts → ./dist/index.ts...
[!] (plugin rpt2) Error: /project/rpt2-issue-102/rollupTest/src/index.ts(1,8): semantic error TS1259: Module '"/project/rpt2-issue-102/rollupTest/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
src/index.ts
Error: /project/rpt2-issue-102/rollupTest/src/index.ts(1,8): semantic error TS1259: Module '"/project/rpt2-issue-102/rollupTest/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
    at error (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:21936:12)
    at Object.error (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:22659:20)
    at Object.error (/project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:22113:42)
    at RollupContext.error (/project/rpt2-issue-102/rollupTest/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:20259:30)
    at /project/rpt2-issue-102/rollupTest/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29527:23
    at Array.forEach (<anonymous>)
    at printDiagnostics (/project/rpt2-issue-102/rollupTest/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29500:17)
    at Object.transform (/project/rpt2-issue-102/rollupTest/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29785:17)
    at /project/rpt2-issue-102/rollupTest/node_modules/rollup/dist/shared/rollup.js:22868:37
```

Once you fix that, it will finally build successfully. Even that old version of rpt2 will rebuild fine (it has too many cache misses etc, but seems to work) manually.

But `npm run dev` will still freeze up. So the issue seems to likely be a bug within that old version of Rollup.

With latest Rollup (`2.75.6`) and its built-in watch mode, it rebuilds fine on all changes, and runs _much_ faster too.

So closing as this was likely an upstream bug and is no longer an issue in current versions.
