### ISSUE TITLE
Plugin should ignore corrupted cache

### ISSUE THREAD

**Issue by ezolenko** [ezolenko/rollup-plugin-typescript2#13]
Sometimes cache gets corrupted, and plugin throws JSON exception (when build interrupted in wrong place).

```
[10:30:58] Error: ./.cache/0e05bd66949fbb4a048b752195b45acaa4973026/code/cache/1ebf05433ba5ed0b148851cac444c0fb84ba87c1: Unexpected end of JSON input
    at error (D:\source\scr\screeps-ts\node_modules\rollup\dist\rollup.js:170:12)
    at D:\source\scr\screeps-ts\node_modules\rollup\dist\rollup.js:8926:6
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

Should catch and fallback instead. Alternatively, use transactions.

Workaround -- cleaning cache and rebuilding.

**Comment by ezolenko** [comment]
In 0.11.1 now
