### ISSUE TITLE
externals not working

### ISSUE THREAD

**Issue by zwhitchcox** [ezolenko/rollup-plugin-typescript2#198]
#### What happens and why it is wrong

So, I can tell rollup that there are peer dependencies AKA externals, through the `options.externals` option.

But this plugin throws an error that it cannot find the module when a module is external. The module is a peer dependency and you're not supposed to be able to find the module.

#### Versions
- typescript: 3.7.3
- rollup: 1.27.8
 - rollup-plugin-typescript2: 0.25.3

#### rollup.config.js
```js
import typescript from 'rollup-plugin-typescript2'
import pkg from './package.json'

export default {
  input: 'src/index.tsx',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      exports: 'named',
      sourcemap: true
    },
    {
      file: pkg.module,
      format: 'es',
      exports: 'named',
      sourcemap: true
    }
  ],
  external: ["react", "@material-ui/core"],
  plugins: [
    typescript({
      rollupCommonJSResolveHack: true,
      clean: true
    }),
  ]
}
```

#### tsconfig.json
```json
{
  "compilerOptions": {
    "outDir": "build",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom", "es2016", "es2017"],
    "sourceMap": true,
    "allowJs": false,
    "declaration": true,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "build", "dist", "example", "rollup.config.js"]
}
```
#### package.json

```json
{
  "name": "@zecos/inputs-mui",
  "version": "0.0.0",
  "description": "rapidly prototype react material design form inputs",
  "author": "Zane Hitchcox",
  "license": "MIT",
  "repository": "zecos/inputs-md",
  "main": "dist/index.js",
  "module": "dist/index.es.js",
  "jsnext:main": "dist/index.es.js",
  "engines": {
    "node": ">=8",
    "npm": ">=5"
  },
  "scripts": {
    "test": "cross-env CI=1 react-scripts-ts test --env=jsdom",
    "test:watch": "react-scripts-ts test --env=jsdom",
    "build": "rollup -c",
    "start": "rollup -c -w",
    "prepare": "yarn run build",
    "predeploy": "cd example && yarn install && yarn run build",
    "deploy": "gh-pages -d example/build"
  },
  "peerDependencies": {
    "prop-types": "^15.5.4",
    "react-dom": "^15.0.0 || ^16.0.0",
    "react": "*",
    "@material-ui/core": "*",
    "mobx": "*"
  },
  "devDependencies": {
    "@svgr/rollup": "^2.4.1",
    "@types/jest": "^23.1.5",
    "@types/react": "^16.3.13",
    "@types/react-dom": "^16.0.5",
    "babel-core": "^6.26.3",
    "babel-runtime": "^6.26.0",
    "cross-env": "^5.1.4",
    "gh-pages": "^1.2.0",
    "react-dom": "^16.4.1",
    "react-scripts-ts": "^2.16.0",
    "rollup": "^1.27.8",
    "rollup-plugin-babel": "^3.0.7",
    "rollup-plugin-commonjs": "^9.1.3",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-peer-deps-external": "^2.2.0",
    "rollup-plugin-postcss": "^1.6.2",
    "rollup-plugin-typescript2": "^0.25.3",
    "rollup-plugin-url": "^1.4.0",
    "typescript": "^3.7.3"
  },
  "files": [
    "dist"
  ],
  "dependencies": {
    "@material-ui/types": "^4.1.1"
  }
}
```

#### plugin output with verbosity 3

```
loaded rollup.config.js with warnings
(!) You have passed an unrecognized option
Unknown input option: verbosity. Allowed options: acorn, acornInjectPlugins, cache, chunkGroupingSize, context, experimentalCacheExpiry, experimentalOptimizeChunks, experimentalTopLevelAwait, external, inlineDynamicImports, input, manualChunks, moduleContext, onwarn, perf, plugins, preserveModules, preserveSymlinks, shimMissingExports, strictDeprecations, treeshake, watch

src/index.tsx → dist/index.js, dist/index.es.js...
[!] (plugin rpt2) Error: /home/zwhitchcox/dev/zecos/inputs-mui/src/index.tsx(3,27): semantic error TS2307: Cannot find module '@material-ui/core'.
src/index.tsx
Error: /home/zwhitchcox/dev/zecos/inputs-mui/src/index.tsx(3,27): semantic error TS2307: Cannot find module '@material-ui/core'.
    at error (/home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup/dist/rollup.js:5363:30)
    at throwPluginError (/home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup/dist/rollup.js:11716:12)
    at Object.error (/home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup/dist/rollup.js:12685:24)
    at Object.error (/home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup/dist/rollup.js:11915:38)
    at RollupContext.error (/home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at /home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at _.each (/home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9342:14)
    at printDiagnostics (/home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/home/zwhitchcox/dev/zecos/inputs-mui/node_modules/rollup-plugin-typescript2/src/index.ts:235:5)
```

**Comment by zwhitchcox** [comment]
I fixed this issue by adding

`declare module "@material-ui/core" `

to my typings.d.ts file

**Comment by agilgur5** [comment]
This is an old issue, but as it never got a response and was being referenced by other users, thought it would be good to respond to it with the proper solution.

### peerDeps and devDeps

The newer https://github.com/ezolenko/rollup-plugin-typescript2/issues/277#issuecomment-1112504639 gives a more detailed answer, but summarizing here: peerDeps generally _also_ need to be installed as devDeps if they are used in development.
While the error is slightly different here (due to an older version of TS; it's the same error code `TS2307`), given the workaround written by OP above, I believe this for the same reason as that issue: TS needs typing information for your peerDeps if you use them in your code in order to type-check that your code is using the peerDeps properly according to their types.
As the peerDep is not installed as a devDep, its typing information can't be found in `node_modules` and so TS throws this error. TS's current error message for this same error code mentions "type declarations" now as well to clarify this kind of situation.

That is a correct error and `tsc` should give the same error, as the typing information truly _can't_ be found.

### workaround

Adding `declare module "@material-ui/core"` is a workaround that allows TS to find a type declaration for the dep, but not any actual typings, so it won't be able to properly type-check with this compared to using the actual dep's typings (basically everything is `any` or `unknown` with this workaround). The optimal solution would be to install as a devDep as well so that the actual typings can be found.
