### ISSUE TITLE
Monorepo: caching logic fails when using yarn workspace

### ISSUE THREAD

**Issue by ael-g** [ezolenko/rollup-plugin-typescript2#232]
Hi,
I have a monorepo managed with lerna and yarn, I started without using yarn workspaces, everything built fine with tsdx.
When I enabled yarn workspaces, juste changing:
```
# lerna.json
+ "useWorkspaces": true,

# package.json
+  "workspaces": {
+    "packages": [
+      "packages/*"
+    ]
+  },
```

None of my packages build anymore and are failing with this error:
```
yarn run v1.12.3
$ tsdx build --target node --format cjs
✓ Creating entry file 4.1 secs
(typescript) Error: ENOENT: no such file or directory, rename './.rts2_cache_cjs/rpt2_121e96229b238ff988af731a4cd7041299f06b93/code/cache_' -> './.rts2_cache_cjs/rpt2_121e96229b238ff988af731a4cd7041299f06b93/code/cache'
Error: ENOENT: no such file or directory, rename './.rts2_cache_cjs/rpt2_121e96229b238ff988af731a4cd7041299f06b93/code/cache_' -> './.rts2_cache_cjs/rpt2_121e96229b238ff988af731a4cd7041299f06b93/code/cache'
    at Object.renameSync (fs.js:643:3)
    at RollingCache.roll (/Users/ael/work/inshteam/Inshallah-Server/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23992:12)
    at TsCache.done (/Users/ael/work/inshteam/Inshallah-Server/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24805:24)
    at Object._ongenerate (/Users/ael/work/inshteam/Inshallah-Server/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:26803:21)
    at Object.generateBundle (/Users/ael/work/inshteam/Inshallah-Server/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:26779:18)
    at /Users/ael/work/inshteam/Inshallah-Server/node_modules/rollup/dist/shared/node-entry.js:13117:25
```

Here are my conf files:
**tsconfig.json**
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "baseUrl": ".",
    "types": [
      "jest"
    ],
    "paths": {
      "src/*": [
        "../ksdjkqsjd"
      ]
    },
    "typeRoots": [
      "./node_modules/@types"
    ],
    "skipLibCheck": true
  },
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

**verbosity 3**
```
rpt2: typescript version: 3.6.4
rpt2: tslib version: 1.9.3
rpt2: rollup version: 1.32.1
rpt2: rollup-plugin-typescript2 version: 0.21.2
rpt2: plugin options:
{
    "typescript": "version 3.6.4",
    "verbosity": 3,
    "cacheRoot": "./.rts2_cache_cjs",
    "tsconfigDefaults": {
        "compilerOptions": {
            "sourceMap": true,
            "declaration": true,
            "jsx": "react"
        }
    },
    "tsconfigOverride": {
        "compilerOptions": {
            "target": "esnext"
        }
    },
    "check": true,
    "clean": false,
    "include": [
        "*.ts+(|x)",
        "**/*.ts+(|x)"
    ],
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "useTsconfigDeclarationDir": false,
    "transformers": [],
    "objectHashIgnoreUnknownHack": false
}
rpt2: rollup config:
{
    "chunkGroupingSize": 5000,
    "experimentalCacheExpiry": 10,
    "inlineDynamicImports": false,
    "input": "***/src/index.ts",
    "perf": false,
    "plugins": [
        {
            "name": "node-resolve"
        },
        {
            "name": "json"
        },
        {},
        {
            "name": "rpt2"
        },
        {
            "name": "babel"
        },
        {
            "name": "replace"
        },
        {
            "name": "sourcemaps"
        }
    ],
    "strictDeprecations": false
}
rpt2: tsconfig path: ***/tsconfig.json
```
I tried with version *0.27.1* of the plugin but same error.
And I see a large proportion of cache miss during the build.

Thanks for your help!

**Comment by agilgur5** [comment]
Not totally sure what's going on here, but seems like you're using an old version version of TSDX based on the `./.rts2_cache_cjs/` path that I changed back in November: https://github.com/formium/tsdx/pull/329

**Comment by agilgur5** [comment]
Closing this as stale as no further response was given by OP and versions were outdated.

It's also very possible that the move to workspaces actually changed the location of the cache and caused this issue, so `clean: true` may in fact be temporarily required, if not more (e.g. cleaning npm cache etc). In any case, difficult to gleam any more without more information or a proper minimal reproduction

**Comment by agilgur5** [comment]
Took a look at this again and thought it sounded familiar... and yep, this seems to duplicate a few issues: https://github.com/jaredpalmer/tsdx/issues/892 and https://github.com/jaredpalmer/tsdx/issues/892, which were fixed by https://github.com/jaredpalmer/tsdx/pull/896 downstream and here in #243.

#243 was merged ~3 months after this issue was created
