### ISSUE TITLE
Typescript module commonjs: "Module resolves to 'CommonJS'. This is incompatible with rollup..."

### ISSUE THREAD

**Issue by Kapcash** [ezolenko/rollup-plugin-typescript2#258]
#### What happens and why it is wrong
I'm trying to bundle a Nodejs Typescript CLI, targeting commonjs.
But I can't make it work with this Typescript module target and I'm getting confused here.

I'd like to have **`ts-node` working**, so I have to set `module: 'commonjs'`. Using `esnext` breaks it.

I looks like I can't have both `rollup` and `ts-node` working at the same time...
**I'm trying to understand why using `module: 'commonjs'` isn't working with this plugin as running `yarn tsc` works fine with my setup?**

#### Environment

Nodejs: 14.15.4 (tried in 15.3.0 as well)

##### Versions

```text
npmPackages:
    rollup: ^2.35.1 => 2.35.1 
    rollup-plugin-typescript2: ^0.29.0 => 0.29.0 
    typescript: ^4.1.2 => 4.1.2 
```

#### rollup.config.js

<details>
  <summary>`rollup.config.js`: </summary>

```javascript
import uglify from 'rollup-plugin-uglify';
import commonjs from '@rollup/plugin-commonjs'
import typescriptPlugin from 'rollup-plugin-typescript2';
import resolve from '@rollup/plugin-node-resolve'
import ts from 'typescript'
import pkg from './package.json'

export default {
  input: 'src/index.ts',
  output: {
    file: pkg.main,
    format: 'cjs',
  },
  external: [
    ...Object.keys(pkg.dependencies || {})
  ],
  plugins: [
    resolve(),
    typescriptPlugin({
      typescript: ts,
      rollupCommonJSResolveHack: true,
    }),
    commonjs(),
    process.env.NODE_ENV === 'production' && uglify()
  ],
};
```
</details>

#### tsconfig.json

<details>
  <summary>`tsconfig.json`: </summary>

```json
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["es2019"],
    "module": "CommonJS",
    "moduleResolution": "node",
    "baseUrl": ".",
    "outDir": "dist",
    "strict": false,
    "allowJs": false,
    "sourceMap": false,
    "removeComments": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "types": [
      "@types/node",
      "@types/jest"
    ],
    "paths": {
      "src/*": [ "src/*" ],
   }
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "dist"
  ]
}
```
</details>

#### package.json

<details>
  <summary>`package.json`: </summary>

```json
{
  "name": "vue-parser-to-class-component",
  "version": "1.0.0",
  "main": "dist/index.js",
  "type": "commonjs",
  "files": [
    "dist"
  ],
  "dependencies": {
    "chalk": "^4.1.0",
    "minimist": "^1.2.5",
    "mkdirp": "^1.0.4",
    "vue-template-compiler": "^2.6.12"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/preset-env": "^7.12.11",
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^11.0.1",
    "@types/jest": "^26.0.19",
    "@types/node": "^14.14.11",
    "babel-jest": "^26.6.3",
    "jest": "^26.6.3",
    "rollup": "^2.35.1",
    "rollup-plugin-typescript2": "^0.29.0",
    "rollup-plugin-uglify": "^6.0.4",
    "ts-jest": "^26.4.4",
    "ts-node": "^9.1.1",
    "typescript": "^4.1.2",
    "typescript-parser": "^2.6.1"
  }
}
```
</details>

#### plugin output with verbosity 3

<details>
  <summary>plugin output with verbosity 3: </summary>

```
$ rollup -c

src/index.ts → dist/index.js...
[!] Error: Incompatible tsconfig option. Module resolves to 'CommonJS'. This is incompatible with rollup, please use 'module: "ES2015"' or 'module: "ESNext"'.
Error: Incompatible tsconfig option. Module resolves to 'CommonJS'. This is incompatible with rollup, please use 'module: "ES2015"' or 'module: "ESNext"'.
    at checkTsConfig (/Users/florentcatiau/projects/vue-parser-to-class-component/node_modules/rollup-plugin-typescript2/src/check-tsconfig.ts:9:9)
    at parseTsConfig (/Users/florentcatiau/projects/vue-parser-to-class-component/node_modules/rollup-plugin-typescript2/src/parse-tsconfig.ts:50:2)
    at Object.options (/Users/florentcatiau/projects/vue-parser-to-class-component/node_modules/rollup-plugin-typescript2/src/index.ts:88:64)
    at /Users/florentcatiau/projects/vue-parser-to-class-component/node_modules/rollup/dist/shared/rollup.js:19997:36
    at getInputOptions (/Users/florentcatiau/projects/vue-parser-to-class-component/node_modules/rollup/dist/shared/rollup.js:19990:61)
    at rollupInternal (/Users/florentcatiau/projects/vue-parser-to-class-component/node_modules/rollup/dist/shared/rollup.js:19937:72)
    at build (/Users/florentcatiau/projects/vue-parser-to-class-component/node_modules/rollup/dist/bin/rollup:1464:20)
    at runRollup (/Users/florentcatiau/projects/vue-parser-to-class-component/node_modules/rollup/dist/bin/rollup:1646:21)

error Command failed with exit code 1.
```
</details>

**Comment by ezolenko** [comment]
Module is required by rollup -- it only understands es2015 / esnext / es2020.

If you need to have different options in tsconfig for tsc and for rollup look at `tsconfigOverride`/`tsconfig`/`tsconfigDefaults` options in readme.
