### ISSUE TITLE
Unexpected token error while webpack working great

### ISSUE THREAD

**Issue by NatsuDawn** [ezolenko/rollup-plugin-typescript2#26]
## Problem
I'm working on angular(4+) aot compile things, and I can get a output with webpack. In order to get a better performance and smaller bundle size, I try rollup these days, but got a puzzling error.
```
{ Error: Unexpected token
    at error (/Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:177:12)
    at Module.error$1 [as error] (/Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:8434:2)
    at tryParse (/Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:8133:10)
    at new Module (/Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:8169:14)
    at /Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:10010:17
  code: 'PARSE_ERROR',
  pos: 4126,
  loc:
   { file: '/Users/xiatianhan/Coding/Tech/newBuild/captial/.tmp/aot/.tmp/src/app/app/app-ng2.module.ngfactory.ts',
     line: 63,
     column: 57 },
  frame: '61: import * as import52 from \'@angular/animations/browser\';\n62: import * as import53 from \'ionic-angular/components/app/app-root\';\n63: class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {\n                                  ^\n64:   _CommonModule_0:import2.CommonModule;\n65:   _ɵba_1:import3.ɵba;' }
```

It's should be a legal grammar, and the verison(2.1.6 or 2.4.2) and tsconfig of typescript I used to compile with webpack and rollup is the same.

## Rollup Config
```
rollup.rollup({
entry: '.tmp/aot/.tmp/src/app/app/app-ng2.module.ngfactory.ts',
    sourceMap: false,
    format: 'iife',
    onwarn: function (warning) {
        if (warning.code === 'THIS_IS_UNDEFINED') {
            return;
        }
        console.warn(warning.message);
    },
    external: [
        '@jdb/ng2-lib'
    ],
    paths: {
        '@jdb/ng2-lib': 'ng2lib'
    },
    globals: {
        '@jdb/ng2-lib': 'ng2lib'
    },
    plugins: [
        angular({
            exclude: ['node_modules/ionic-angular/**/*'],
            preprocessors: {
                template: template => minify(template, htmlminOpts),
                style: scss => {
                    let css = sass.renderSync({
                        data: scss
                    }).css;
                    css = postcss([autoprefixer({browsers: [
                        "iOS 7",
                        "iOS 8",
                        "Android 4"
                    ]})]).process(css).css;
                    return cssmin.minify(css).styles;
                },
            }
        }),
        nodeResolve({
            jsnext: true,
            module: true
        }),
        typescript({
            tsconfig: "tsconfig.build.json",
            verbosity: 3,
            clean: true,
            check: false,
            abortOnError: false
        }),
        commonjs({
            include: [
                'node_modules/rxjs/**',
                'node_modules/query-string/**',
                'node_modules/strict-uri-encode/index.js'
            ]
        })
        // uglify()
    ]
})
```

##  Log
The whole log
```
start rollup
Typescript version: 2.4.2
rpt2: Typescript version: 2.4.2
rpt2: Options: {
    "tsconfig": "tsconfig.build.json",
    "verbosity": 3,
    "clean": true,
    "check": false,
    "abortOnError": false,
    "cacheRoot": "/Users/xiatianhan/Coding/Tech/newBuild/captial/.rpt2_cache",
    "include": [
        "*.ts+(|x)",
        "**/*.ts+(|x)"
    ],
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "rollupCommonJSResolveHack": false
}
{ config:
   { compilerOptions:
      { target: 'es5',
        module: 'es2015',
        moduleResolution: 'node',
        sourceMap: true,
        emitDecoratorMetadata: true,
        experimentalDecorators: true,
        lib: [Object],
        noImplicitAny: false,
        suppressImplicitAnyIndexErrors: true,
        outDir: '.tmp/out',
        allowJs: true,
        rootDir: '.',
        baseUrl: '.',
        paths: [Object] },
     include: [ '.tmp/**/*' ],
     exclude:
      [ '.tmp/common_modules/**/*',
        'node_modules',
        './src/main.aot.ts',
        'dist',
        'temp/**/*',
        '**/*.spec.ts',
        '.tmp/main-aot.ts' ],
     compileOnSave: false,
     angularCompilerOptions: { genDir: './.tmp/aot', skipMetadataEmit: true } } }
rpt2: rollupConfig: {
    "entry": ".tmp/aot/.tmp/src/app/app/app-ng2.module.ngfactory.ts",
    "sourceMap": false,
    "format": "iife",
    "external": [
        "@jdb/ng2-lib"
    ],
    "paths": {
        "@jdb/ng2-lib": "ng2lib"
    },
    "globals": {
        "@jdb/ng2-lib": "ng2lib"
    },
    "plugins": [
        {
            "name": "angular"
        },
        {
            "name": "node-resolve"
        },
        {},
        {
            "name": "commonjs"
        }
    ]
}
rpt2: Ambient types:
rpt2:     /Users/xiatianhan/Coding/Tech/newBuild/captial/.tmp/src/app/global.d.ts
rpt2:     /Users/xiatianhan/Coding/Tech/newBuild/captial/.tmp/src/app/typings.d.ts
rpt2:     /Users/xiatianhan/Coding/Tech/newBuild/captial/.tmp/src/tradeCaptial/global.d.ts
rpt2:     /Users/xiatianhan/Coding/Tech/newBuild/captial/node_modules/@types/angular/index.d.ts
rpt2:     /Users/xiatianhan/Coding/Tech/newBuild/captial/node_modules/@types/jquery/index.d.ts
rpt2:     /Users/xiatianhan/Coding/Tech/newBuild/captial/node_modules/@types/node/index.d.ts
rpt2: ambient types changed, redoing all semantic diagnostics
rpt2: cleaning cache: /Users/xiatianhan/Coding/Tech/newBuild/captial/.rpt2_cache/dfae67991e14befd28a9f94f64044ea70e5c3030
{ Error: Unexpected token
    at error (/Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:177:12)
    at Module.error$1 [as error] (/Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:8434:2)
    at tryParse (/Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:8133:10)
    at new Module (/Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:8169:14)
    at /Users/xiatianhan/Coding/Tech/newBuild/@jdb/ngu/node_modules/rollup/dist/rollup.js:10010:17
  code: 'PARSE_ERROR',
  pos: 4126,
  loc:
   { file: '/Users/xiatianhan/Coding/Tech/newBuild/captial/.tmp/aot/.tmp/src/app/app/app-ng2.module.ngfactory.ts',
     line: 63,
     column: 57 },
  frame: '61: import * as import52 from \'@angular/animations/browser\';\n62: import * as import53 from \'ionic-angular/components/app/app-root\';\n63: class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {\n                                  ^\n64:   _CommonModule_0:import2.CommonModule;\n65:   _ɵba_1:import3.ɵba;' }
```

**Comment by ezolenko** [comment]
Doesn't look like anything makes it into typescript plugin -- the error is in rollup proper. Try increasing verbosity to 4 and see if there are more lines with `rpt2:` prefix...

Do you actually have `ɵ` char in `import0.ɵNgModuleInjector<import1.AppModule>` in your source file, or is that something added by one of the plugins? Is the file saved as utf-8 or some other encoding?

**Comment by NatsuDawn** [comment]
I make typescript plugin commented, and the error is still there. It's nothing to do with typescript plugin, I'm sorry i made a mistake. It's should be a rollup problem, Gonna close the issue.
