### ISSUE TITLE
Source file not found error when running in "watch" mode

### ISSUE THREAD

**Issue by danielvy** [ezolenko/rollup-plugin-typescript2#271]
#### What happens and why it is wrong

When running rollup in watch mode, the project will initially compile but changes to some files that trigger rollup watch, will cause a source file not found error from rp2:

```
[!] (plugin rpt2) Error: Could not find source file: '/<path removed>/watch-err/source/lib/module1.ts'.
Error: Could not find source file: '/<path removed>/watch-err/source/lib/module1.ts'.
    at getValidSourceFile (/<path removed>/watch-err/node_modules/typescript/lib/typescript.js:153646:29)
    at Object.getSyntacticDiagnostics (/<path removed>/watch-err/node_modules/typescript/lib/typescript.js:153896:52)
    at /<path removed>/watch-err/node_modules/rollup-plugin-typescript2/src/index.ts:306:23
    at TsCache.getDiagnostics (/<path removed>/watch-err/node_modules/rollup-plugin-typescript2/src/tscache.ts:298:49)
    at TsCache.getSyntacticDiagnostics (/<path removed>/watch-err/node_modules/rollup-plugin-typescript2/src/tscache.ts:238:15)
    at /<path removed>/watch-err/node_modules/rollup-plugin-typescript2/src/index.ts:304:15
    at /<path removed>/watch-err/node_modules/rollup-plugin-typescript2/src/tscache.ts:183:61
    at arrayEach (/<path removed>/watch-err/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at Function._.each [as forEach] (/<path removed>/watch-err/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9368:14)
    at TsCache.walkTree (/<path removed>/watch-err/node_modules/rollup-plugin-typescript2/src/tscache.ts:183:4)
```

[Repository with reproduction code](https://github.com/danielvy/rollup-ts-vue-watch-error)

#### Steps to reproduce:

1. Run `rollup -c rollup.config.js --watch`
2. Trigger rollup watch by re-saving `module2.ts` or `index.ts`. Note that triggering watch with `module1.ts` will not produce the error.

I assume this is related to the directory structure of the project which uses `baseUrl` to point up to the "_lib_" dir.  Also, I was not able to reproduce this without Vue.

#### Environment

MacOS 10.15
Node 16

**Comment by agilgur5** [comment]
### another workaround

Per the log, this seems to be an issue in the cache logic (with Vue only for whatever reason):

> ```
>     at TsCache.walkTree (/<path removed>/watch-err/node_modules/rollup-plugin-typescript2/src/tscache.ts:183:4)
> ```

So, as such, one can also set `clean: true` as a workaround to skip the cache entirely.

### bit of investigation

When searching the error at hand, you'll get a lot of results from other TS integrations, such as `ts-jest`. Interestingly enough, `ts-jest` hit into this same error when they introduced a cache: https://github.com/kulshekhar/ts-jest/issues/1506 .

From that issue, it's also not clear that the few PRs around that have _entirely_ fixed the bug. It's likely a race condition (similar to #243), so they've probably solved several races but not necessarily all of them.
Some of those might be usable within rpt2 too, but we have different caching mechanisms and very different code around it. I've looked at the cache code a bit and couldn't pinpoint why this issue occurs, but if it is indeed a race condition, then its due to an anomaly, so something _unexpected_ is happening that the code doesn't handle.

Also, some comments suggest that this is due to cyclic dependencies (which may relate to the Vue plugin), and indeed the cache code runs a [different graph algorithm](https://github.com/ezolenko/rollup-plugin-typescript2/blob/03cfb048adcf39de56bd4566dc9a7300534a3cc1/src/tscache.ts#L182) depending if it the module graph is acyclic or not.

A `verbosity: 3` log was not provided here as the issue template asks, so can't tell if it's due to that. The `verbosity: 3` log would output detailed information about the whole module graph, so looking at could be quite helpful for debugging.

**Comment by agilgur5** [comment]
Hmm... looking at some older watch mode issues (see the new [label](https://github.com/ezolenko/rollup-plugin-typescript2/labels/scope%3A%20watch%20mode)) it seems that was supposed to have been fixed by #32. And that it's popped up a few times.

That and #95 also suggest the issue might be within the `LanguageServiceHost` implementation, and unfortunately, that is the most "gotcha" sparsely documented thing in the TS Compiler API (see also #351, https://github.com/ezolenko/rollup-plugin-typescript2/issues/234#issuecomment-1139202740), so it's often pretty difficult to find out what's going on there without straight up debugging TS's own source code.

**Comment by agilgur5** [comment]
Ah I've traced the bug and figured it out! Turns out this is a regression that was actually _caused by_ the fix for #95.

This [line](https://github.com/ezolenko/rollup-plugin-typescript2/commit/c86e07bc0f2f875e3953ee651871830351d38452?w=1#diff-49ecc36f34e1f45bd5ed5039646b8eaa1e919ecf4bcdfed5eae5c356bf11bff8R39) was added to `setSnapshot` but not to `getScriptSnapshot`.
`getScriptSnapshot` is _only_ called in the callback for `walkTree`, so that explains why this wasn't found until now.

I'll write up a PR for this in a jiffy!
Thanks for the repro @danielvy! I was able to change this code locally in `node_modules` of your repro and then the error went away, so can confirm the fix works 🙂

**Comment by danielvy** [comment]
@agilgur5 

Great news. Thank you for taking the time to fix this. I can go back to using rollup's watch instead of relying on node-watch during development.

**Comment by agilgur5** [comment]
#364 has been released in [`0.33.0`](https://github.com/ezolenko/rollup-plugin-typescript2/releases/0.33.0.1)
