### ISSUE TITLE
[!] (plugin rpt2) Error: semantic error TS2571: Object is of type 'unknown'.

### ISSUE THREAD

**Issue by ruihildt** [ezolenko/rollup-plugin-typescript2#279]
#### What happens and why it is wrong
When I update to TypeScript >= 4.3.3 (coming from TypeScript 4.3.2), when running the watch command, I have the following error appearing for a seemingly random file in my Vue 2 project:

```
[1] [!] (plugin rpt2) Error: /home/path/static/src/js/views/Component.ts(79,15): semantic error TS2571: Object is of type 'unknown'.
```

There's nothing of note on line 79, and in VSCode, there's no TS error picked up. I tried deleting that component, and another similar error pops up with another component.

What can I do to fix this?

#### Environment
Ubuntu 20.04
NPM 6.14.13
Node v14.16.1

##### Versions
```
rollup: ^2.56.3 => 2.56.3 
    rollup-plugin-typescript2: ^0.30.0 => 0.30.0 
    typescript: ^4.3.3 => 4.4.2

```

#### rollup.config.js
<details>
  <summary>`rollup.config.js`: </summary>

```
import alias from '@rollup/plugin-alias';
import replace from '@rollup/plugin-replace';
import json from '@rollup/plugin-json';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import typeScript from 'rollup-plugin-typescript2';
import { terser } from 'rollup-plugin-terser';
import commonjs from '@rollup/plugin-commonjs';
import { eslint } from 'rollup-plugin-eslint';
import babel from '@rollup/plugin-babel';

const production = !process.env.ROLLUP_WATCH;

export default {
  input: './static/src/js/main.ts',
  output: {
    file: './static/dist/js/app.js',
    format: 'umd',
    name: 'name',
    sourcemap: !production,
  },
  plugins: [
    alias({
      entries: [
        { find: 'vue', replacement: require.resolve('vue/dist/vue.esm.js') },
        { find: 'jszip', replacement: require.resolve('jszip/dist/jszip.js') },
      ],
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify(production ? 'production' : 'development'),
      'process.env.VUE_ENV': JSON.stringify('browser'),
      preventAssignment: true,
    }),
    eslint({
      throwOnError: production,
      throwOnWarning: production,
    }),
    nodeResolve({
      browser: true,
    }),
    commonjs(),
    json(),
    typeScript({
      clean: production,
    }),
    production && terser(),
    production && babel({ babelHelpers: 'bundled' }),
  ],
};

```

</details>

#### tsconfig.json
<details>
  <summary>`tsconfig.json`: </summary>

```
{
    "compilerOptions": {
        "baseUrl": "./static/src/js",
        "rootDir": "./static/src/js",
        "allowJs": false,
        "alwaysStrict": true,
        "esModuleInterop": true,
        "noImplicitReturns": true,
        "noUnusedLocals": false,
        "noUnusedParameters": true,
        "skipLibCheck": true,
        "strict": true,
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "incremental": true,
        "lib": ["es2017", "dom"],
        "resolveJsonModule": true
    }
}
```
</details>

#### package.json
<details>
  <summary>`package.json`: </summary>

```
{
  "name": "web-project",
  "private": true,
  "scripts": {
    "build": "gulp build && rollup -c",
    "watch": "concurrently \"gulp watch\" \"rollup -cw\"",
    "test": "jest",
    "lint": "eslint static/src/ --ext .ts",
    "fix": "npm run lint -- --fix",
    "coverage": "jest --coverage"
  },
  "devDependencies": {
    "@babel/plugin-proposal-object-rest-spread": "^7.14.7",
    "@intlify/eslint-plugin-vue-i18n": "^0.11.1",
    "@rollup/plugin-alias": "^3.1.5",
    "@rollup/plugin-babel": "^5.3.0",
    "@rollup/plugin-commonjs": "^19.0.2",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^13.0.4",
    "@rollup/plugin-replace": "^2.4.2",
    "@types/jest": "^26.0.24",
    "@typescript-eslint/eslint-plugin": "^4.29.3",
    "@typescript-eslint/parser": "^4.29.3",
    "@vue/test-utils": "^1.2.2",
    "autoprefixer": "^10.3.3",
    "breakpoint-sass": "^2.7.1",
    "concurrently": "^6.2.1",
    "cssnano": "^5.0.8",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.1",
    "eslint-plugin-vue": "^7.17.0",
    "gulp": "^4.0.2",
    "gulp-imagemin": "^7.1.0",
    "gulp-postcss": "^9.0.0",
    "gulp-sass": "^4.1.1",
    "gulp-sourcemaps": "^2.6.5",
    "jest": "^26.5.1",
    "jest-extended": "^0.11.5",
    "plugin-error": "^1.0.1",
    "postcss": "^8.3.6",
    "prettier": "^2.3.2",
    "rollup": "^2.56.3",
    "rollup-plugin-eslint": "^7.0.0",
    "rollup-plugin-typescript2": "^0.30.0",
    "ts-jest": "^26.5.5",
    "typescript": "^4.3.3",
    "vue-template-compiler": "^2.6.12"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@types/file-saver": "^2.0.3",
    "@types/js-cookie": "^2.2.7",
    "@types/uuid": "^8.3.1",
    "axios": "^0.21.1",
    "bulma": "^0.9.3",
    "bulma-o-steps": "^1.1.0",
    "camelcase-keys": "^6.2.2",
    "file-saver": "^2.0.5",
    "js-cookie": "^2.2.1",
    "jszip": "^3.7.1",
    "qrcode.vue": "^1.7.0",
    "rollup-plugin-terser": "^7.0.2",
    "snakecase-keys": "^4.0.2",
    "tslib": "^2.3.1",
    "uuid": "^8.3.2",
    "vue": "^2.6.12",
    "vue-i18n": "^8.25.0",
    "vue-router": "^3.5.2",
    "vuex": "^3.6.2"
  }
}

```
</details>

#### plugin output with verbosity 3
<details>
  <summary>plugin output with verbosity 3: </summary>

```

[1] [!] (plugin rpt2) Error: /home/path/static/src/js/views/Component.ts(79,15): semantic error TS2571: Object is of type 'unknown'.
[1] static/src/js/views/Component.ts
[1] Error: /home/path/static/src/js/views/Component.ts(79,15): semantic error TS2571: Object is of type 'unknown'.
[1]     at error (/home/path/node_modules/rollup/dist/shared/rollup.js:151:30)
[1]     at throwPluginError (/home/path/node_modules/rollup/dist/shared/rollup.js:19344:12)
[1]     at Object.error (/home/path/node_modules/rollup/dist/shared/rollup.js:20013:20)
[1]     at Object.error (/home/path/node_modules/rollup/dist/shared/rollup.js:19520:38)
[1]     at RollupContext.error (/home/path/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
[1]     at /home/path/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
[1]     at arrayEach (/home/path/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
[1]     at Function._.each [as forEach] (/home/path/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9368:14)
[1]     at printDiagnostics (/home/path/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
[1]     at Object.transform (/home/path/node_modules/rollup-plugin-typescript2/src/index.ts:244:5)

```

</details>

**Comment by ruihildt** [comment]
After further debugging and help from another person, it's actually a change that only appears in the TS 4.4 release notes: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables

I have added the flag `"useUnknownInCatchVariables": false` to the `tsconfig.json` to type the error in catch blocks to `unknown` by default.
