### ISSUE TITLE
class constructor throws type error with rpt2 but not tsc

### ISSUE THREAD

**Issue by yarinsa** [ezolenko/rollup-plugin-typescript2#297]
#### What happens and why it is wrong

I can define / access class variables.
When defining in the constructor 
```ts
class User {
constructor(name:string)
}
```
Result => build fails with the error I am getting in the header.

When defining as class property 
```ts
class User {
constructor(name:string)
}
```
Result => build pass. 

When defining as class property and trying to access
```ts
class User {
constructor(name:string) {
this.name
}
}
```
Result => build fails with the error I am getting in the header.

I am having trouble believing it never happened to anyone as this package is popular. Couldn't find any open issue about this. The parsed ts-config seems fine in the logs. 

#### Environment

MacOS Monterey 
VS-Code
Node 17.3.1

##### Versions

```
 npmPackages:
    rollup-plugin-typescript2: 0.31.2 => 0.31.2 
    typescript: ^4.4.4 => 4.5.5 

```

#### rollup.config.js

I don't use one

#### tsconfig.json

<details>
  <summary>`tsconfig.json`: </summary>

```json5
{
  "compilerOptions": {
    "target": "es5",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "declaration": true,
    "moduleResolution": "node",
    "inlineSourceMap": true,
    "downlevelIteration": true
  },
  "exclude": ["./__tests__", "dist", "**/__mocks__/**"],
  "include": ["src"]
}
```

</details>

#### plugin output with verbosity 3 - failure case

<details>
  <summary>plugin output with verbosity 3: </summary>

```bash
$ rm -rf dist && yarn vite build
$ /Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.bin/vite build
vite v2.8.3 building for production...
rpt2: built-in options overrides: {
    "noEmitHelpers": false,
    "importHelpers": true,
    "noResolve": false,
    "noEmit": false,
    "inlineSourceMap": false,
    "outDir": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/placeholder",
    "moduleResolution": 2,
    "allowNonTsExtensions": true,
    "module": 5
}
rpt2: parsed tsconfig: {
    "options": {
        "target": 1,
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "declaration": true,
        "moduleResolution": 2,
        "inlineSourceMap": false,
        "downlevelIteration": true,
        "configFilePath": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/tsconfig.json",
        "noEmitHelpers": false,
        "importHelpers": true,
        "noResolve": false,
        "noEmit": false,
        "outDir": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/placeholder",
        "allowNonTsExtensions": true,
        "module": 5
    },
    "fileNames": [
        "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts",
        "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts",
        "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/storage.ts",
        "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/types.ts"
    ],
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "raw": {
        "compilerOptions": {
            "target": "es5",
            "allowSyntheticDefaultImports": true,
            "esModuleInterop": true,
            "declaration": true,
            "moduleResolution": "node",
            "inlineSourceMap": true,
            "downlevelIteration": true
        },
        "exclude": [
            "./__tests__",
            "dist",
            "**/__mocks__/**"
        ],
        "include": [
            "src"
        ],
        "compileOnSave": false
    },
    "errors": [],
    "wildcardDirectories": {
        "/users/yarinsasson/documents/work/user-management-service/sdk/src": 1
    },
    "compileOnSave": false
}
rpt2: typescript version: 4.5.5
rpt2: tslib version: 2.3.1
rpt2: rollup version: 2.67.2
rpt2: rollup-plugin-typescript2 version: 0.31.2
rpt2: plugin options:
{
    "verbosity": 3,
    "check": true,
    "clean": false,
    "cacheRoot": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2",
    "include": [
        "*.ts+(|x)",
        "**/*.ts+(|x)"
    ],
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "useTsconfigDeclarationDir": false,
    "tsconfigOverride": {},
    "transformers": [],
    "tsconfigDefaults": {},
    "objectHashIgnoreUnknownHack": false,
    "cwd": "/Users/yarinsasson/Documents/Work/user-management-service/sdk",
    "typescript": "version 4.5.5"
}
rpt2: rollup config:
{
    "input": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts",
    "context": "globalThis",
    "preserveEntrySignatures": "strict",
    "plugins": [
        {
            "name": "alias"
        },
        {
            "name": "vite:modulepreload-polyfill"
        },
        {
            "name": "vite:resolve"
        },
        {
            "name": "vite:html-inline-proxy"
        },
        {
            "name": "vite:css"
        },
        {
            "name": "vite:esbuild"
        },
        {
            "name": "vite:json"
        },
        {
            "name": "vite:wasm"
        },
        {
            "name": "vite:worker"
        },
        {
            "name": "vite:worker-import-meta-url"
        },
        {
            "name": "vite:asset"
        },
        {
            "name": "sourcemaps"
        },
        {
            "name": "rpt2"
        },
        {
            "name": "vite:define"
        },
        {
            "name": "vite:css-post"
        },
        {
            "name": "vite:watch-package-data"
        },
        {
            "name": "vite:build-html"
        },
        {
            "name": "commonjs"
        },
        {
            "name": "vite:data-uri"
        },
        {
            "name": "rollup-plugin-dynamic-import-variables"
        },
        {
            "name": "vite:asset-import-meta-url"
        },
        {
            "name": "vite:build-import-analysis"
        },
        {
            "name": "vite:esbuild-transpile"
        },
        {
            "name": "vite:terser"
        },
        {
            "name": "vite:reporter"
        },
        {
            "name": "vite:load-fallback"
        }
    ]
}
rpt2: tsconfig path: /Users/yarinsasson/Documents/Work/user-management-service/sdk/tsconfig.json
rpt2: included:
[
    "*.ts+(|x)",
    "**/*.ts+(|x)"
]
rpt2: excluded:
[
    "*.d.ts",
    "**/*.d.ts"
]
rpt2: Ambient types:
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/@types/estree/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/@types/semver/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/faker/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/js-yaml/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/json-schema/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/json-stable-stringify/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/json5/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/jsonwebtoken/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/minimatch/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/minimist/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/node/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/normalize-package-data/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/parse-json/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/websocket/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/ws/index.d.ts
rpt2: transpiling '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts'
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/code/cache/8661eed392c11e612e9472818fb33610261775b5'
rpt2:     cache hit
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/syntacticDiagnostics/cache/8661eed392c11e612e9472818fb33610261775b5'
rpt2:     cache hit
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/semanticDiagnostics/cache/8661eed392c11e612e9472818fb33610261775b5'
rpt2:     cache hit
rpt2: generated declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts'
transforming (1) src/index.tsrpt2: transpiling '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts'
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/code/cache/4926919e7c8797b34661afb3926fead78e96e050'
rpt2:     cache miss
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/syntacticDiagnostics/cache/4926919e7c8797b34661afb3926fead78e96e050'
rpt2:     cache miss
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/semanticDiagnostics/cache/4926919e7c8797b34661afb3926fead78e96e050'
rpt2:     cache miss
✓ 1 modules transformed.
[rpt2] /Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts(3,10): semantic error TS2339: Property 'options' does not exist on type 'AuthClient'.
file: /Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts
error during build:
Error: /Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts(3,10): semantic error TS2339: Property 'options' does not exist on type 'AuthClient'.
    at error (/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup/dist/shared/rollup.js:160:30)
    at throwPluginError (/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup/dist/shared/rollup.js:21831:12)
    at Object.error (/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup/dist/shared/rollup.js:22556:20)
    at Object.error (/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup/dist/shared/rollup.js:22008:42)
    at RollupContext.error (/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17311:30)
    at /Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25144:23
    at arrayEach (/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:585:11)
    at Function.forEach (/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9465:14)
    at printDiagnostics (/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25117:14)
    at Object.transform (/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:30271:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

#### plugin output with verbosity 3 - success case

<details>
  <summary>plugin output with verbosity 3: </summary>

```
command.
➜  sdk git:(develop) ✗ yarn build
yarn run v1.22.17
$ rm -rf dist && yarn vite build
$ /Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.bin/vite build
vite v2.8.3 building for production...
rpt2: built-in options overrides: {
    "noEmitHelpers": false,
    "importHelpers": true,
    "noResolve": false,
    "noEmit": false,
    "inlineSourceMap": false,
    "outDir": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/placeholder",
    "moduleResolution": 2,
    "allowNonTsExtensions": true,
    "module": 5
}
rpt2: parsed tsconfig: {
    "options": {
        "target": 1,
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "declaration": true,
        "moduleResolution": 2,
        "inlineSourceMap": false,
        "downlevelIteration": true,
        "configFilePath": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/tsconfig.json",
        "noEmitHelpers": false,
        "importHelpers": true,
        "noResolve": false,
        "noEmit": false,
        "outDir": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/placeholder",
        "allowNonTsExtensions": true,
        "module": 5
    },
    "fileNames": [
        "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts",
        "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts",
        "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/storage.ts",
        "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/types.ts"
    ],
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "raw": {
        "compilerOptions": {
            "target": "es5",
            "allowSyntheticDefaultImports": true,
            "esModuleInterop": true,
            "declaration": true,
            "moduleResolution": "node",
            "inlineSourceMap": true,
            "downlevelIteration": true
        },
        "exclude": [
            "./__tests__",
            "dist",
            "**/__mocks__/**"
        ],
        "include": [
            "src"
        ],
        "compileOnSave": false
    },
    "errors": [],
    "wildcardDirectories": {
        "/users/yarinsasson/documents/work/user-management-service/sdk/src": 1
    },
    "compileOnSave": false
}
rpt2: typescript version: 4.5.5
rpt2: tslib version: 2.3.1
rpt2: rollup version: 2.67.2
rpt2: rollup-plugin-typescript2 version: 0.31.2
rpt2: plugin options:
{
    "verbosity": 3,
    "check": true,
    "clean": false,
    "cacheRoot": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2",
    "include": [
        "*.ts+(|x)",
        "**/*.ts+(|x)"
    ],
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "useTsconfigDeclarationDir": false,
    "tsconfigOverride": {},
    "transformers": [],
    "tsconfigDefaults": {},
    "objectHashIgnoreUnknownHack": false,
    "cwd": "/Users/yarinsasson/Documents/Work/user-management-service/sdk",
    "typescript": "version 4.5.5"
}
rpt2: rollup config:
{
    "input": "/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts",
    "context": "globalThis",
    "preserveEntrySignatures": "strict",
    "plugins": [
        {
            "name": "alias"
        },
        {
            "name": "vite:modulepreload-polyfill"
        },
        {
            "name": "vite:resolve"
        },
        {
            "name": "vite:html-inline-proxy"
        },
        {
            "name": "vite:css"
        },
        {
            "name": "vite:esbuild"
        },
        {
            "name": "vite:json"
        },
        {
            "name": "vite:wasm"
        },
        {
            "name": "vite:worker"
        },
        {
            "name": "vite:worker-import-meta-url"
        },
        {
            "name": "vite:asset"
        },
        {
            "name": "sourcemaps"
        },
        {
            "name": "rpt2"
        },
        {
            "name": "vite:define"
        },
        {
            "name": "vite:css-post"
        },
        {
            "name": "vite:watch-package-data"
        },
        {
            "name": "vite:build-html"
        },
        {
            "name": "commonjs"
        },
        {
            "name": "vite:data-uri"
        },
        {
            "name": "rollup-plugin-dynamic-import-variables"
        },
        {
            "name": "vite:asset-import-meta-url"
        },
        {
            "name": "vite:build-import-analysis"
        },
        {
            "name": "vite:esbuild-transpile"
        },
        {
            "name": "vite:terser"
        },
        {
            "name": "vite:reporter"
        },
        {
            "name": "vite:load-fallback"
        }
    ]
}
rpt2: tsconfig path: /Users/yarinsasson/Documents/Work/user-management-service/sdk/tsconfig.json
rpt2: included:
[
    "*.ts+(|x)",
    "**/*.ts+(|x)"
]
rpt2: excluded:
[
    "*.d.ts",
    "**/*.d.ts"
]
rpt2: Ambient types:
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/@types/estree/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/@types/semver/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/faker/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/js-yaml/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/json-schema/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/json-stable-stringify/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/json5/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/jsonwebtoken/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/minimatch/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/minimist/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/node/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/normalize-package-data/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/parse-json/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/websocket/index.d.ts
rpt2:     /Users/yarinsasson/Documents/Work/user-management-service/node_modules/@types/ws/index.d.ts
rpt2: transpiling '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts'
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/code/cache/8661eed392c11e612e9472818fb33610261775b5'
rpt2:     cache hit
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/syntacticDiagnostics/cache/8661eed392c11e612e9472818fb33610261775b5'
rpt2:     cache hit
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/semanticDiagnostics/cache/8661eed392c11e612e9472818fb33610261775b5'
rpt2:     cache hit
rpt2: generated declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts'
transforming (1) src/index.tsrpt2: transpiling '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts'
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/code/cache/65f0e23b922100607ae070f3b9ae38c383a98f98'
rpt2:     cache hit
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/syntacticDiagnostics/cache/65f0e23b922100607ae070f3b9ae38c383a98f98'
rpt2:     cache hit
rpt2:     cache: '/Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.cache/rollup-plugin-typescript2/rpt2_78d7eb8a74b0b6f25c11de8eecad86647833265f/semanticDiagnostics/cache/65f0e23b922100607ae070f3b9ae38c383a98f98'
rpt2:     cache hit
rpt2: generated declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts'
✓ 2 modules transformed.
rendering chunks (1)...rpt2: generating target 1
rpt2: rolling caches
rpt2: generating missed declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/storage.ts'
rpt2: generating missed declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/types.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts' to 'index.d.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts' to 'authClient.d.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/storage.ts' to 'storage.d.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/types.ts' to 'types.d.ts'
dist/index.d.ts        0.01 KiB
dist/authClient.d.ts   0.11 KiB
dist/storage.d.ts      0.06 KiB
dist/types.d.ts        0.11 KiB
dist/sdk.umd.js        0.30 KiB / gzip: 0.20 KiB
rendering chunks (1)...rpt2: generating target 2
rpt2: rolling caches
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts' to 'index.d.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts' to 'authClient.d.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/storage.ts' to 'storage.d.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/types.ts' to 'types.d.ts'
dist/index.d.ts        0.01 KiB
dist/authClient.d.ts   0.11 KiB
dist/storage.d.ts      0.06 KiB
dist/types.d.ts        0.11 KiB
dist/sdk.cjs.js        0.22 KiB / gzip: 0.17 KiB
rendering chunks (1)...rpt2: generating target 3
rpt2: rolling caches
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/index.ts' to 'index.d.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/authClient.ts' to 'authClient.d.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/storage.ts' to 'storage.d.ts'
rpt2: emitting declarations for '/Users/yarinsasson/Documents/Work/user-management-service/sdk/src/types.ts' to 'types.d.ts'
dist/index.d.ts        0.01 KiB
dist/authClient.d.ts   0.11 KiB
dist/storage.d.ts      0.06 KiB
dist/types.d.ts        0.11 KiB
dist/sdk.es.js         0.33 KiB / gzip: 0.19 KiB
```
</details>

**Comment by yarinsa** [comment]
It seems like I am gonna have to set the `check` flag to false.
I have tried to run the build without cache. I also tried running `tsc -b`.   tsc doesn't emit any problems (and static tslint). 
I also supplied my instance of 'typescript'. None of the above seems to work. 

I think it's a major feature since failing the build if the type checking failed is a core feature of TS. 
I have no problem tracking down the issue and contributing, but I need some guidance @ezolenko

**Comment by ezolenko** [comment]
That supposed to work I think -- rpt2 uses this syntax itself in [host.ts](https://github.com/ezolenko/rollup-plugin-typescript2/blob/master/src/host.ts) for example, and it builds itself with an older version of itself...

**Comment by yarinsa** [comment]
Just an update in case someone runs into this issue.
I deep-dived into the plugin code. Few configurations that I didn't have in my tsconfig and the Plugin 'added' (checked by comparing the resolved config vs provided one) are these ones: 
```
    noEmitHelpers: false,
    importHelpers: true,
    noResolve: false,
    inlineSourceMap: false,
    allowNonTsExtensions: true,
    module: 5,
```

I am not sure if this is the problem , but It might save some debugging for someone. 
I ended up removing this plugin and checking my types using `vite-plugin-checker` and generating declarations using 'vite-plugin-dts'.

**Comment by agilgur5** [comment]
> Few configurations that I didn't have in my tsconfig and the Plugin 'added' (checked by comparing the resolved config vs provided one) are these ones:

These are mentioned [in the docs](https://github.com/ezolenko/rollup-plugin-typescript2#some-compiler-options-are-forced) that they are forced as they're required for rpt2 / Rollup compat

> I am not sure if this is the problem , but It might save some debugging for someone.

Probably not, but there's some head-scratching issues where the output is not equivalent to `tsc` that are very confusing as this plugin is intentionally simple in how it wraps the TS API.
My guess is that they might be related to other plugins on the chain but I really don't know

**Comment by agilgur5** [comment]
Ok, so I looked into this and created a minimal repro [here](https://stackblitz.com/edit/rpt2-issue-297?file=src/index.ts) and was unable to reproduce this.

It took me a bit to even create the reproduction as OP's first edit broke all the code examples, causing errors in both `tsc` and rpt2. It also made the first two examples duplicates of each other. And it removed the error message from the comment and after that, the title was changed as well to remove the error message.
So that was _incredibly_ confusing.
I've edited it myself to merge the first edit with the original version to something that actually works and makes sense.

In any case, the minimal environment linked above has all 3 examples and rpt2 passes on all 3 of them. So the issue you're having is not due to rpt2, but your configuration.

Specifically, you wrote:

> #### rollup.config.js
> I don't use one

But left out a _very important_ detail, that you're using _Vite_ to build instead of Rollup. And then you did not provide your `vite.config.js` either...

I had to interpret your logs and your previous comment to figure that you were using Vite:

> ```
> $ /Users/yarinsasson/Documents/Work/user-management-service/sdk/node_modules/.bin/vite build
> ```

> checking my types using `vite-plugin-checker` and generating declarations using `vite-plugin-dts`.

Vite already supports TypeScript [out-of-the-box](https://vitejs.dev/guide/features.html#typescript) with `esbuild`. So if you wanted to use rpt2 for type-checking, you'd have to either disable that support or run rpt2 _first_, before `esbuild`. Running it after `esbuild` would mean rpt2 is actually reading the compiled JS results.
I'm not sure if Vite even supports that and this plugin was built for Rollup before Vite even existed. The Vite team should probably have reached out here to make sure the integration (mentioned in [their docs](https://vitejs.dev/guide/using-plugins.html#conditional-application)) works instead of ad-hoc issues by users who wouldn't know the implementation details... 😕 

The error you're getting is also similar to https://github.com/ezolenko/rollup-plugin-typescript2/issues/235, which is due to a bug within `rollup-plugin-vue` https://github.com/vuejs/rollup-plugin-vue/issues/311 (not this plugin). It's possible Vite has a similar bug. #352 experienced a similar error with Vite as well.

So this either a bug in Vite itself or a misconfiguration. But as it's not reproducible with just rpt2 and Rollup, it's not a bug in this library.
