### ISSUE TITLE
Pug import error -- missing declaration

### ISSUE THREAD

**Issue by void-dragon** [ezolenko/rollup-plugin-typescript2#303]
I have written a little custom rollup plugin to import and convert pug files.
```js
class PugImporter {
    constructor() {
        this.name = "pug"
    }

    resolveId(source, importer) {
        if (source.endsWith(".pug")) {
            const out = path.join(path.dirname(importer), source)
            console.log("resolver", out)
            return out
        }

        return null
    }

    load(id) {
        if (id.endsWith(".pug")) {
            const result = pug.renderFile(id)
            return `export default \`${result}\``
        }

        return null
    }

}

export default {
    input: "src/index.ts",
    output: {
        dir: "www",
        format: "es",
    },
    plugins: [
        copy({
            targets: [
                {src: "src/index.html", dest: "www"},
            ]
        }),
        postcss({
            extract: "index.css",
            minimize: true,
        }),
        new PugImporter(),
        nodeResolve(),
        typescript(),
    ]
}
```

This works perfectly fine for JS files.
BUT in combination with this plugin, ONLY the `import .. from` statement leads to an error.
The method resolveId of the plugin is in this case never called.

```js
import "./stepone.pug" // works fine
import HtmlTemplate from "./stepone.pug" // produces module not found error

[!] (plugin rpt2) Error: /home/zacharias/Workspace/hatch/client/src/view/register/stepone.ts(4,18): semantic error TS2307: Cannot find module './stepone.pug' or its corresponding type declarations.
src/view/register/stepone.ts
Error: /home/zacharias/Workspace/hatch/client/src/view/register/stepone.ts(4,18): semantic error TS2307: Cannot find module './stepone.pug' or its corresponding type declarations.
    at error (/home/zacharias/Workspace/hatch/client/node_modules/rollup/dist/shared/rollup.js:159:30)
    at throwPluginError (/home/zacharias/Workspace/hatch/client/node_modules/rollup/dist/shared/rollup.js:21818:12)
    at Object.error (/home/zacharias/Workspace/hatch/client/node_modules/rollup/dist/shared/rollup.js:22544:20)
    at Object.error (/home/zacharias/Workspace/hatch/client/node_modules/rollup/dist/shared/rollup.js:21995:42)
    at RollupContext.error (/home/zacharias/Workspace/hatch/client/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at /home/zacharias/Workspace/hatch/client/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/home/zacharias/Workspace/hatch/client/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:530:11)
    at Function._.each [as forEach] (/home/zacharias/Workspace/hatch/client/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9410:14)
    at printDiagnostics (/home/zacharias/Workspace/hatch/client/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/home/zacharias/Workspace/hatch/client/node_modules/rollup-plugin-typescript2/src/index.ts:244:5)

```

**Comment by ezolenko** [comment]
I think the problem is typescript expects some type declaration for the module (so it can check that module does indeed contain `HtmlTemplate` and to know what type `HtmlTemplate` is. I assume `pug.renderFile` returns js code, not ts? If so, you might have to manually write types for it (`declare module` stuff)

**Comment by agilgur5** [comment]
Pretty sure `tsc` will give the same error for this, as declarations indeed seem to be missing for your Pug files. So this isn't an rpt2 error, it's just a TS usage thing.

Can see a similar issue here https://github.com/s-panferov/awesome-typescript-loader/issues/380#issuecomment-282782014 for details on how to get TS to resolve such files.
