### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by theS3ns** [ezolenko/rollup-plugin-typescript2#45]
import typescript from 'rollup-plugin-typescript2';

-node_modules
-src
--main.js
--....
-rollup.config.js
-tsconfig.json
-package.json

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at typescript (...\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:19760:21)
    at Object.<anonymous> (...\rollup.config.js:17:7)
    at Module._compile (module.js:571:32)
    at Object.require.extensions..js (...\node_modules\rollup\bin\rollup:20371:8)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

"rollup": "^0.52.1",
"rollup-plugin-json": "^2.3.0",
"rollup-plugin-typescript2": "^0.8.4"

build command: "build": "rollup -c"

**Comment by ezolenko** [comment]
You need to add `"typescript": "^2.6.2"` to your `package.json` (or whichever version you need, must be 2.0+)

**Comment by theS3ns** [comment]
Thanks, this fixed. This ticket can be closed...
