### ISSUE TITLE
vite 5.1.1 `error during build`

### ISSUE THREAD

**Issue by nestle49** [ezolenko/rollup-plugin-typescript2#468]
```
vite v5.1.1 building for production...
✓ 0 modules transformed.
error during build:

    at Object._object (/Users/developer/PhpstormProjects/foodsoul-kit/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27290:18)
    at Object.dispatch (/Users/developer/PhpstormProjects/foodsoul-kit/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27257:31)
    at /Users/developer/PhpstormProjects/foodsoul-kit/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27318:19
    at Array.forEach (<anonymous>)
    at Object._object (/Users/developer/PhpstormProjects/foodsoul-kit/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27314:22)
    at Object.dispatch (/Users/developer/PhpstormProjects/foodsoul-kit/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27257:31)
    at /Users/developer/PhpstormProjects/foodsoul-kit/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27318:19
    at Array.forEach (<anonymous>)
    at Object._object (/Users/developer/PhpstormProjects/foodsoul-kit/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27314:22)
    at Object.dispatch (/Users/developer/PhpstormProjects/foodsoul-kit/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27257:31)
```

**Comment by agilgur5** [comment]
Do not remove the issue template, it is there for a reason.
An error message with 0 context is not actionable.

**Comment by nestle49** [comment]
I get this error after upgrade vue version from 3.4.15 (needed 3.4.15 or later)

Related issue
https://github.com/vuejs/core/issues/10300

**Comment by agilgur5** [comment]
> I get this error after upgrade vue version from 3.4.15 (needed 3.4.16 or later)

That sounds like an issue in Vue then, not rpt2.

> Related issue (with minimal package and config, I can't reproduce project)
> [vuejs/core#10300](https://github.com/vuejs/core/issues/10300)

The config there is pretty far from [minimal](https://stackoverflow.com/help/minimal-reproducible-example), and is a Vite config not a Rollup config. There is also no source code provided, only config. Maintainers there said something very similar.

**Comment by nestle49** [comment]
> > I get this error after upgrade vue version from 3.4.15 (needed 3.4.16 or later)
> 
> That sounds like an issue in Vue then, not rpt2.
> 
> > Related issue (with minimal package and config, I can't reproduce project)
> > [vuejs/core#10300](https://github.com/vuejs/core/issues/10300)
> 
> The config there is pretty far from [minimal](https://stackoverflow.com/help/minimal-reproducible-example), and is a Vite config not a Rollup config. Notably, it does not seem to run rpt2 before `esbuild` either, which can cause [a variety of issues](https://github.com/ezolenko/rollup-plugin-typescript2/issues/305#issuecomment-1200261316) as rpt2 is operating on untyped JS at that point. There is also no source code provided, only config.
> 
> Note that maintainers there said something very similar as well, in much shorter form and despite the significantly more details you provided there than here.

Thanks, yes I think that vue problem

I created reproduction https://github.com/nestle49/minimalReproduction
And I updated vue issue

**Comment by agilgur5** [comment]
> I created reproduction https://github.com/nestle49/minimalReproduction

Again, this is pretty far from [minimal](https://stackoverflow.com/help/minimal-reproducible-example), and still has all the Vite/`esbuild` issues I mentioned above as well

**Comment by nestle49** [comment]
Upstream problem answered in vue, if you're interested
