### ISSUE TITLE
Cannot read property 'warn' of undefined

### ISSUE THREAD

**Issue by jakewtaylor** [ezolenko/rollup-plugin-typescript2#75]
#### What happens and why it is wrong

I can't use the plugin because it throws an error:

```
TypeError: Error Loading C:\path\to\file.ts: Cannot read propert 'warn' of undefined
    at new RollupContext (C:\path\to\node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:10:47)
    at transform (C:\path\to\node_modules\rollup-plugin-typescript2\src\index.ts:185:21)
    at C:\path\to\node_modules\rollup\src\utils\transform.js:11:28
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

#### Environment 

Windows 10

#### Versions
- typescript: 2.8.3 (I think - this could be the problem, I'm not entirely sure which version of typescript is being used)
- rollup: 0.31.0
- rollup-plugin-typescript2: 6.5.0

**Comment by ezolenko** [comment]
You need a more recent version of rollup, latest is `0.58.1` currently, this plugin supports a few version back but iirc nothing below 0.40-something will work.
